### ISSUE TITLE
support Stack walk with  function with FPO 

### ISSUE THREAD

**Issue by isugarhome** [ssbssa/heob#18]
do you have plan to  support Stack walk with FPO（Frame Pointer optimization)  function,

**Comment by ssbssa** [comment]
I suppose you mean for 32bit, because for 64bit it shouldn't matter if FPO is enabled or not.

The problem is, to get correct stacktraces with FPO for 32bit, you would have to use the debug information as well, because it should contain the frame location of the current IP.
It's possible to do, but as a result the program gets a **LOT** slower.

Nowadays most programs are 64bit (or at least they should be), and for 32bit you can still disable FPO as you said, thus I saw no real gain to implement that.
